package com.xfw.hattened.misc;

public enum UserInput {
    LEFT_ALT_PRESSED,
    LEFT_ALT_RELEASED,
    SCROLL_UP,
    SCROLL_DOWN,
    LEFT_MOUSE_PRESSED,
    LEFT_MOUSE_RELEASED,
    RIGHT_MOUSE_PRESSED,
    RIGHT_MOUSE_RELEASED,
    MIDDLE_MOUSE_PRESSED
}